# server
server:
  port: 8000

# actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - httptrace
          - busrefresh
          - info
#          - metrics
#          - prometheus

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# spring
spring:
  application:
    name: api-gateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: password
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: user-sercice # create user
          uri: lb://user-service
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}


# logging
logging:
  level:
    com.hw: debug